#!/usr/bin/env python

import os
import argparse
import subprocess
from urllib.parse import urlparse
from pathlib import Path


parser = argparse.ArgumentParser(description="Clone git repo into a tidy path.")
parser.add_argument("repo", help="The git repo to clone")

args = parser.parse_args()

uri = args.repo
result = urlparse(uri)

base_path = "/home/njenan/git/src/"

split = result.path.split("/")
subpath = "/".join(split[1:-1])
repo = split[-1]


Path(base_path + result.netloc + "/" + subpath).mkdir(parents=True, exist_ok=True)
destination = base_path + result.netloc + "/" + subpath

print("cloning repo to '" + destination + "'")
commands = ["git", "-C", destination, "clone", uri]

subprocess.call(commands)

